site_name: Diamond, Dahye
repo_name: kangdaia/profile
repo_url: https://github.com/kangdaia/
nav:
    - Home: index.md
    - Projects:
        - "What Makes You Happy?": 
            - projects/project-happy.md
theme:
    name: material
    language: en
    features:
        - header.autohide
        - navigation.tabs
        - content.code.copy
    font:
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/github
        logo: fontawesome/solid/gem
    palette:
        scheme: slate
        primary: custom
        accent: pink
markdown_extensions:
    - md_in_html
    - tables
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Korean
      link: /ko/
      lang: ko

extra_css:
    - stylesheets/extra.css

extra_javascript:
    - javascripts/extra.js